# Generated by Django 4.2.2 on 2023-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TGUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Telegram User ID"
                    ),
                ),
                ("chat_id", models.BigIntegerField(verbose_name="Telegram Chat ID")),
                (
                    "username",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Telegram Username"
                    ),
                ),
            ],
            options={
                "db_table": "tg_user",
            },
        ),
    ]
